logging:
    level:
        tk.mybatis: DEBUG
        com.github.wxiaoqi.security.admin: DEBUG
spring:
    application:
        name: user-center
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://116.196.98.85:3306/mydb?useUnicode=true&characterEncoding=UTF-8
        username: jerrymysql
        password: mysqlJerry!1
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.jerry.security.uc.mapper
    xmlLocation: classpath:mapper/**/*.xml
eureka:
#  instance:
#     prefer-ip-address: true
#     ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  token-header: access-token
  pri-key:
      path: client/pri.key
  pub-key:
    path: client/pub.key

