spring:
      application:
             name:jerry-config
      profiles:
             active:native

server:
  port: 8750 #启动端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
