spring:
      application:
             name: jerry-config
      cloud:
              config:
                  server:
                      git:
                          uri: https://github.com/renjinlong/Jerry-Config.git


server:
  port: 8750 #启动端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
